export const ADD_BREED = 'ADD_BREED';
// export const REMOVE_MOVIE_FAVORITE = 'REMOVE_MOVIE_FAVORITE';
// export const GET_MOVIES = 'GET_MOVIES';
// export const GET_MOVIES_DETAILS = 'GET_MOVIES_DETAILS';
